---
name: 'Splash'

services:

  ha_proxy:
    image: display-splash-ha_proxy
    build:
      context: .
      dockerfile: .docker/images/haproxy/ha_proxy
    hostname: haproxy
    restart: always
    depends_on:
      splash:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8050:8050"
    networks:
      - backend
    healthcheck:
      test: |
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/80; echo -e "GET / HTTP/1.1\nConnection: close\n" >&3; cat <&3 | grep -q "200 OK"'
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 30s

  splash:
    image: display-splash
    command: --maxrss 4096 --disable-browser-caches
    build:
      context: .
      dockerfile: .docker/images/splash/splash_screen
    deploy:
      replicas: 15
    restart: always
    env_file:
      - .env
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:8050 || exit 1
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 20s

networks:
  backend:
    name: development_backend
    external: true
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "172.16.30.1"
    ipam:
      config:
        - subnet: 172.16.30.0/24
