version: '3.5'

services:

  flask_lb:
    image: display-flask_lb
    build:
      context: .
      dockerfile: .docker/images/flask_lb/ha_proxy
    hostname: flask_lb
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:7000:7000
    networks:
      - frontend
      - backend

  flask1:
    image: display-flask1
    build:
      context: .
      dockerfile: .docker/images/flask/dockerfile-flask
    hostname: flask1
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./dev_data/flask:/app/data"
    networks:
      - backend

  flask2:
    image: display-flask2
    build:
      context: .
      dockerfile: .docker/images/flask/dockerfile-flask
    hostname: flask2
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./dev_data/flask:/app/data"
    networks:
      - backend

  flask3:
    image: display-flask3
    build:
      context: .
      dockerfile: .docker/images/flask/dockerfile-flask
    hostname: flask3
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./dev_data/flask:/app/data"
    networks:
      - backend

  ha_proxy:
    image: display-splash-ha_proxy
    build:
      context: .
      dockerfile: .docker/images/haproxy/ha_proxy
    hostname: haproxy
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:8050:8050
    networks:
      - frontend
      - backend

  splash1:
    image: display-splash1
    command: --maxrss 4096 --disable-browser-caches
    build:
      context: .
      dockerfile: .docker/images/splash/splash_screen
    hostname: splash1
    restart: always
    env_file:
      - .env
    networks:
      - backend

  splash2:
    image: display-splash2
    command: --maxrss 4096 --disable-browser-caches
    build:
      context: .
      dockerfile: .docker/images/splash/splash_screen
    hostname: splash2
    restart: always
    env_file:
      - .env
    networks:
      - backend

  splash3:
    image: display-splash3
    command: --maxrss 4096 --disable-browser-caches
    build:
      context: .
      dockerfile: .docker/images/splash/splash_screen
    hostname: splash3
    restart: always
    env_file:
      - .env
    networks:
      - backend

  splash4:
    image: display-splash4
    command: --maxrss 4096 --disable-browser-caches
    build:
      context: .
      dockerfile: .docker/images/splash/splash_screen
    hostname: splash4
    restart: always
    env_file:
      - .env
    networks:
      - backend

  splash5:
    image: display-splash5
    command: --maxrss 4096 --disable-browser-caches
    build:
      context: .
      dockerfile: .docker/images/splash/splash_screen
    hostname: splash5
    restart: always
    env_file:
      - .env
    networks:
      - backend

  redis:
    image: display-redis
    hostname: redis
    restart: always
    build:
      context: .
      dockerfile: .docker/images/redis/dockerfile-redis
    volumes:
      - "./dev_data/redis:/data"
    expose:
      - 6379
    networks:
      - backend

  celery_daemon:
    image: display-celery_daemon
    build:
      context: .
      dockerfile: .docker/images/celery_daemon/dockerfile-celery_daemon
    depends_on:
      - redis
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./dev_data/flask:/app/data"
    expose:
      - 5671
    networks:
      - backend

networks:
  frontend:
  backend: