---
name: 'Display'

services:

  flask_lb:
    image: display-dev-flask_lb
    build:
      context: .
      dockerfile: .docker/images/flask_lb/nginx
    hostname: flask_lb
    restart: always
    develop:
      watch:
        - action: sync+restart
          path: ./display/webapp/static
          target: /app/static
          ignore:
            - celery_app/
    depends_on:
      flask_web:
        condition: service_healthy
      flask_ws:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:80"
    networks:
      - backend

  flask_web:
    image: display-dev-flask_web
    build:
      context: .
      dockerfile: .docker/images/flask/dockerfile-flask
      args:
        PORT: 5050
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
    develop:
      watch:
        - action: sync+restart
          path: ./display/
          target: /app/display/
          ignore:
            - celery_app/
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    restart: always
    expose:
      - 5050
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./docker-data/flask:/app/data"
    networks:
      backend:
        ipv4_address: 172.16.30.7
    healthcheck:
      test: curl --fail http://localhost:5050 || exit 1
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 30s

  flask_ws:
    image: display-dev-flask_ws
    build:
      context: .
      dockerfile: .docker/images/flask/dockerfile-flask
      args:
        PORT: 5050
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
    depends_on:
      flask_web:
        condition: service_healthy
    restart: always
    expose:
      - 5050
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./docker-data/flask:/app/data"
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:5050 || exit 1
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 30s

  ha_proxy:
    image: display-splash-ha_proxy
    build:
      context: .
      dockerfile: .docker/images/haproxy/ha_proxy
    hostname: haproxy
    restart: always
    depends_on:
      splash:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8050:8050"
    networks:
      - backend
    healthcheck:
      test: |
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/80; echo -e "GET / HTTP/1.1\nConnection: close\n" >&3; cat <&3 | grep -q "200 OK"'
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 30s

  splash:
    image: display-splash
    command: --maxrss 4096 --disable-browser-caches
    build:
      context: .
      dockerfile: .docker/images/splash/splash_screen
    deploy:
      replicas: 15
    depends_on:
      flask_web:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:8050 || exit 1
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 20s

  celery_daemon:
    image: display-dev-celery_daemon
    build:
      context: .
      dockerfile: .docker/images/celery_daemon/dockerfile-celery_daemon
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
    develop:
      watch:
        - action: sync
          path: ./display/
          target: /app/display/
          ignore:
            - webapp/templates/
            - webapp/static/
            - webapp/home/
            - webapp/auth/
            - webapp/admin/
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    restart: always
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./docker-data/flask:/app/data"
    networks:
      - backend

  celery_beat:
    image: display-dev-celery_beat
    build:
      context: .
      dockerfile: .docker/images/celery_beat/dockerfile-celery_beat
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
    develop:
      watch:
        - action: sync+restart
          path: ./display/
          target: /app/display/
          ignore:
            - webapp/templates/
            - webapp/static/
            - webapp/home/
            - webapp/auth/
            - webapp/admin/
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    restart: always
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./docker-data/flask:/app/data"
    networks:
      - backend

  redis:
    image: display-dev-redis
    hostname: redis
    restart: always
    build:
      context: .
      dockerfile: .docker/images/redis/dockerfile-redis
    volumes:
      - "redis_data:/data"
    expose:
      - 6379
    networks:
      backend:
        ipv4_address: 172.16.30.4
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 5s

  mysql:
    image: display-dev-mysql
    build:
      context: .
      dockerfile: .docker/images/mysql/dockerfile-mysql
    hostname: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.16.30.5
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 5s

networks:
  backend:
    name: development_backend
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "172.16.30.1"
    ipam:
      config:
        - subnet: 172.16.30.0/24

volumes:
  mysql_data:
  redis_data:
