---
name: 'Display'

services:

  flask_web:
    image: display-flask_web
    build:
      context: .
      dockerfile: .docker/images/flask/dockerfile-flask
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
      init_db:
        condition: service_completed_successfully
    deploy:
      replicas: 2
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./docker_data/flask:/app/data"
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:5050 || exit 1
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 30s

  flask_ws:
    image: display-flask_ws
    build:
      context: .
      dockerfile: .docker/images/flask/dockerfile-flask
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
      init_db:
        condition: service_completed_successfully
    deploy:
      replicas: 3
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./docker_data/flask:/app/data"
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:5050 || exit 1
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 30s

  ha_proxy:
    image: display-splash-ha_proxy
    build:
      context: .
      dockerfile: .docker/images/haproxy/ha_proxy
    hostname: haproxy
    restart: always
    depends_on:
      splash:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "127.0.0.1:8050:8050"
    networks:
      - frontend
      - backend
    healthcheck:
      test: |
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/80; echo -e "GET / HTTP/1.1\nConnection: close\n" >&3; cat <&3 | grep -q "200 OK"'
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 30s

  splash:
    image: display-splash
    command: --maxrss 4096 --disable-browser-caches
    build:
      context: .
      dockerfile: .docker/images/splash/splash_screen
    deploy:
      replicas: 15
    restart: always
    env_file:
      - .env
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:8050 || exit 1
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 20s

  celery_daemon:
    image: display-celery_daemon
    build:
      context: .
      dockerfile: .docker/images/celery_daemon/dockerfile-celery_daemon
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
      init_db:
        condition: service_completed_successfully
    deploy:
      replicas: 2
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./docker_data/flask:/app/data"
    networks:
      - backend
    healthcheck:
      test: poetry run celery -A display.celery_app.display_daemon inspect ping --destination celery@$$HOSTNAME
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  celery_beat:
    image: display-celery_beat
    build:
      context: .
      dockerfile: .docker/images/celery_beat/dockerfile-celery_beat
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
      init_db:
        condition: service_completed_successfully
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./docker_data/flask:/app/data"
    networks:
      - backend
    healthcheck:
      test: '[ "$$(find /tmp/beat_live -mmin -1 | wc -l)" != "" ] || false'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis:
    image: display-redis
    hostname: redis
    restart: always
    build:
      context: .
      dockerfile: .docker/images/redis/dockerfile-redis
    volumes:
      - "./docker_data/redis:/data"
    expose:
      - 6379
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 5s

  mysql:
    image: display-mysql
    build:
      context: .
      dockerfile: .docker/images/mysql/dockerfile-mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    restart: always
    env_file:
      - .env
    security_opt:
      - seccomp:unconfined
    volumes:
      - "./docker_data/mysql_data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 5s

  init_db:
    image: display-init_db
    build:
      context: .
      dockerfile: .docker/images/init_db/dockerfile-init-db
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./docker_data/flask:/app/data"
    networks:
      - backend

  autoheal:
    image: willfarrell/autoheal:latest
    hostname: autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    networks:
      - backend

networks:
  frontend:
  backend:
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "172.26.1.1"
    ipam:
      config:
        - subnet: 172.26.1.0/24
