version: '3.5'

services:

  flask:
    image: display-flask
    build:
      context: .
      dockerfile: .docker/images/flask/dockerfile-flask
    hostname: flask
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    ports:
      - 7000:5050
    volumes:
      - "./dev_data/flask:/app/data"
    networks:
      - frontend
      - backend

  ha_proxy:
    image: display-splash-ha_proxy
    build:
      context: .
      dockerfile: .docker/images/haproxy/ha_proxy
    hostname: haproxy
    restart: always
    env_file:
      - .env
    ports:
      - 8050:8050
    networks:
      - frontend
      - backend

  splash1:
    image: display-splash1
    command: --maxrss 4096
    build:
      context: .
      dockerfile: .docker/images/splash/splash_screen
    hostname: splash1
    restart: always
    env_file:
      - .env
    networks:
      - backend

  splash2:
    image: display-splash2
    command: --maxrss 4096
    build:
      context: .
      dockerfile: .docker/images/splash/splash_screen
    hostname: splash2
    restart: always
    env_file:
      - .env
    networks:
      - backend

  splash3:
    image: display-splash3
    command: --maxrss 4096
    build:
      context: .
      dockerfile: .docker/images/splash/splash_screen
    hostname: splash3
    restart: always
    env_file:
      - .env
    networks:
      - backend

  redis:
    image: display-redis
    hostname: redis
    restart: always
    build:
      context: .
      dockerfile: .docker/images/redis/dockerfile-redis
    volumes:
      - "./dev_data/redis:/data"
    expose:
      - 6379
    networks:
      - backend

  celery_daemon:
    image: display-celery_daemon
    build:
      context: .
      dockerfile: .docker/images/celery_daemon/dockerfile-celery_daemon
    depends_on:
      - redis
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - "./dev_data/flask:/app/data"
    expose:
      - 5671
    networks:
      - backend

networks:
  frontend:
  backend: