version: '3.5'

services:

  ha_proxy:
    image: display-splash-ha_proxy-dev
    build:
      context: .
      dockerfile: ./ha_proxy
    hostname: haproxy
    restart: always
    env_file:
      - .env
    ports:
      - 8050:8050
    networks:
      - frontend
      - backend

  splash:
    image: display-splash
    command: --maxrss 4096 --disable-browser-caches
    build:
      context: .
      dockerfile: ./splash_screen
    deploy:
      replicas: 15
    restart: always
    env_file:
      - .env
    networks:
      - backend
    healthcheck:
      test: curl --fail http://localhost:8050 || exit 1
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 20s

  autoheal:
    image: willfarrell/autoheal:latest
    hostname: autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    networks:
      - backend

  mysql:
    image: display-mysql
    build:
      context: .
      dockerfile: ../.docker/images/mysql/dockerfile-mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
    volumes:
      - "../docker_data/mysql_data:/var/lib/mysql"
    networks:
      backend:
        ipv4_address: 172.26.1.5

networks:
  frontend:
  backend:
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "172.26.1.1"
    ipam:
      config:
        - subnet: 172.26.1.0/24
