# Use the latest Python image
FROM python:latest

# Set an environment variable with the directory
# where we'll be running the app
ENV APP /app

# Create the directory and instruct Docker to operate
# from there from now on
RUN mkdir $APP
WORKDIR $APP

# Copy the current directory contents into the container at /app
ADD . $APP

RUN echo "deb http://deb.debian.org/debian/ unstable main contrib non-free" >> /etc/apt/sources.list.d/debian.list
RUN apt-get update
RUN apt-get install -y --no-install-recommends firefox-esr
RUN curl -L https://github.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-linux64.tar.gz | tar xz -C /usr/local/bin

RUN pip install --upgrade pip

# Install the dependencies
RUN pip install -r requirements.txt

COPY ./.docker/files/flask/install.sh .
RUN sed -i -e 's/\r$//' ./install.sh

RUN ./install.sh

RUN rm ./install.sh

# run the command to start the celery daemon
CMD ["/usr/local/bin/celery", "-A", "display.celery_app.display_daemon", "worker", "--loglevel=INFO", "-B", "-O", "fair" , "--without-heartbeat", "--without-gossip", "--without-mingle"]
