# Use the latest Python image
FROM python:3.10.12

# Set an environment variable with the directory
# where we'll be running the app
ENV APP /app

# Create the directory and instruct Docker to operate
# from there from now on
RUN mkdir $APP
WORKDIR $APP

# Copy the current directory contents into the container at /app
ADD . $APP

RUN pip install --upgrade pip

# Install the dependencies
RUN pip install -r requirements.txt

COPY ./.docker/files/flask/install.sh .
RUN sed -i -e 's/\r$//' ./install.sh

RUN ./install.sh

RUN rm ./install.sh

# run the command to start the celery beat
CMD ["/usr/local/bin/celery", "-A", "display.celery_app.display_daemon", "beat", "--loglevel=INFO"]
