"""empty message

Revision ID: 29b338e2e616
Revises: 9d8215528eda
Create Date: 2023-04-04 05:55:58.051328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "29b338e2e616"
down_revision = "9d8215528eda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("role")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("role", mysql.VARCHAR(length=16), nullable=True))

    # ### end Alembic commands ###
