"""added field to defacement tracker

Revision ID: 3d8d6bb7f63d
Revises: 9fc1b12f833c
Create Date: 2024-11-27 09:30:57.175676

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3d8d6bb7f63d"
down_revision = "9fc1b12f833c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("defacementtracker", schema=None) as batch_op:
        batch_op.add_column(sa.Column("force", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("defacementtracker", schema=None) as batch_op:
        batch_op.drop_column("force")

    # ### end Alembic commands ###
