"""empty message

Revision ID: 4e74f69bf04d
Revises: 29b338e2e616
Create Date: 2023-04-04 06:58:31.380987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4e74f69bf04d"
down_revision = "29b338e2e616"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracelog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=True),
        sa.Column("url_hash", sa.String(length=12), nullable=True),
        sa.Column("timestamp", sa.Integer(), nullable=True),
        sa.Column("action", sa.Integer(), nullable=True),
        sa.Column("user", sa.String(length=128), nullable=True),
        sa.Column("result", sa.String(length=512), nullable=True),
        sa.Column("reason", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tracelog", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tracelog_action"), ["action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracelog_timestamp"), ["timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracelog_url_hash"), ["url_hash"], unique=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "username",
            existing_type=mysql.VARCHAR(length=48),
            type_=sa.String(length=128),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "username",
            existing_type=sa.String(length=128),
            type_=mysql.VARCHAR(length=48),
            existing_nullable=True,
        )

    with op.batch_alter_table("tracelog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracelog_url_hash"))
        batch_op.drop_index(batch_op.f("ix_tracelog_timestamp"))
        batch_op.drop_index(batch_op.f("ix_tracelog_action"))

    op.drop_table("tracelog")
    # ### end Alembic commands ###
