"""empty message

Revision ID: 5987837b4638
Revises: 4e74f69bf04d
Create Date: 2023-04-04 07:15:03.053861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5987837b4638"
down_revision = "4e74f69bf04d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracelog", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status_code", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_tracelog_status_code"), ["status_code"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracelog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracelog_status_code"))
        batch_op.drop_column("status_code")

    # ### end Alembic commands ###
