"""added table for defacement texts

Revision ID: 60e983e73d54
Revises: 0ba9ae76fb81
Create Date: 2024-11-22 19:32:48.430956

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60e983e73d54"
down_revision = "0ba9ae76fb81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "templatetexts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("templatetexts")
    # ### end Alembic commands ###
