"""larger picture_hash

Revision ID: 8c4722461eb1
Revises: e810af4e6074
Create Date: 2024-11-26 15:09:23.981881

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "8c4722461eb1"
down_revision = "e810af4e6074"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("defacementtracker", schema=None) as batch_op:
        batch_op.alter_column(
            "picture_hash",
            existing_type=mysql.VARCHAR(length=30),
            type_=sa.String(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("defacementtracker", schema=None) as batch_op:
        batch_op.alter_column(
            "picture_hash",
            existing_type=sa.String(length=128),
            type_=mysql.VARCHAR(length=30),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
