"""defacement table added

Revision ID: 9e81d084bf65
Revises: 60e983e73d54
Create Date: 2024-11-25 13:22:52.912211

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e81d084bf65"
down_revision = "60e983e73d54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "defacements",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("hash", sa.String(length=30), nullable=False),
        sa.Column("header", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("defacements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_defacements_count"), ["count"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_defacements_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_defacements_hash"), ["hash"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_defacements_header"), ["header"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("defacements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_defacements_header"))
        batch_op.drop_index(batch_op.f("ix_defacements_hash"))
        batch_op.drop_index(batch_op.f("ix_defacements_created_at"))
        batch_op.drop_index(batch_op.f("ix_defacements_count"))

    op.drop_table("defacements")
    # ### end Alembic commands ###
