"""added created_at field

Revision ID: 9fc1b12f833c
Revises: 8c4722461eb1
Create Date: 2024-11-26 15:18:23.552546

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9fc1b12f833c"
down_revision = "8c4722461eb1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("defacementtracker", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.Integer(), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_defacementtracker_created_at"), ["created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("defacementtracker", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_defacementtracker_created_at"))
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
