"""empty message

Revision ID: a9d2e16f0480
Revises: 
Create Date: 2023-11-23 08:08:34.281215

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a9d2e16f0480"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_groups_name"), ["name"], unique=True)

    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("flask_decorator", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("flask_decorator"),
    )
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_permissions_name"), ["name"], unique=True)

    op.create_table(
        "tracelog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=True),
        sa.Column("hash", sa.String(length=12), nullable=True),
        sa.Column("timestamp", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=25), nullable=True),
        sa.Column("user", sa.String(length=128), nullable=True),
        sa.Column("result", sa.String(length=25), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tracelog", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tracelog_action"), ["action"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tracelog_hash"), ["hash"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tracelog_result"), ["result"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracelog_status_code"), ["status_code"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracelog_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=True),
        sa.Column("fullname", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("pw_hash", sa.String(length=512), nullable=True),
        sa.Column("active", sa.Integer(), nullable=True),
        sa.Column("api_key", sa.String(length=512), nullable=True),
        sa.Column("api_key_lookup", sa.String(length=128), nullable=True),
        sa.Column("last_login", sa.Integer(), nullable=True),
        sa.Column("approval", sa.Integer(), nullable=True),
        sa.Column("system", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "groupmembers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group", sa.Integer(), nullable=True),
        sa.Column("user", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group"], ["groups.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["user"], ["users.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "grouppermissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("permission", sa.Integer(), nullable=True),
        sa.Column("group", sa.Integer(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group"], ["groups.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["permission"], ["permissions.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("grouppermissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_grouppermissions_value"), ["value"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("grouppermissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_grouppermissions_value"))

    op.drop_table("grouppermissions")
    op.drop_table("groupmembers")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("tracelog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracelog_timestamp"))
        batch_op.drop_index(batch_op.f("ix_tracelog_status_code"))
        batch_op.drop_index(batch_op.f("ix_tracelog_result"))
        batch_op.drop_index(batch_op.f("ix_tracelog_hash"))
        batch_op.drop_index(batch_op.f("ix_tracelog_action"))

    op.drop_table("tracelog")
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permissions_name"))

    op.drop_table("permissions")
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_groups_name"))

    op.drop_table("groups")
    # ### end Alembic commands ###
