"""empty message

Revision ID: c6ff14758bd5
Revises: 
Create Date: 2023-04-06 10:05:03.452009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c6ff14758bd5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("created", sa.Integer(), nullable=True),
        sa.Column("updated", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_groups_name"), ["name"], unique=True)

    op.create_table(
        "tracelog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=True),
        sa.Column("hash", sa.String(length=12), nullable=True),
        sa.Column("timestamp", sa.Integer(), nullable=True),
        sa.Column("action", sa.Integer(), nullable=True),
        sa.Column("user", sa.String(length=128), nullable=True),
        sa.Column("result", sa.Integer(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tracelog", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tracelog_action"), ["action"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tracelog_hash"), ["hash"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tracelog_result"), ["result"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracelog_status_code"), ["status_code"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tracelog_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=True),
        sa.Column("password", sa.String(length=512), nullable=True),
        sa.Column("created", sa.Integer(), nullable=True),
        sa.Column("updated", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "groupmembers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("groupid", sa.Integer(), nullable=True),
        sa.Column("userid", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["groupid"], ["groups.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["userid"], ["users.id"], onupdate="cascade", ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("groupmembers")
    op.drop_table("users")
    with op.batch_alter_table("tracelog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracelog_timestamp"))
        batch_op.drop_index(batch_op.f("ix_tracelog_status_code"))
        batch_op.drop_index(batch_op.f("ix_tracelog_result"))
        batch_op.drop_index(batch_op.f("ix_tracelog_hash"))
        batch_op.drop_index(batch_op.f("ix_tracelog_action"))

    op.drop_table("tracelog")
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_groups_name"))

    op.drop_table("groups")
    # ### end Alembic commands ###
