"""empty message

Revision ID: cb2cedf37b19
Revises: c6ff14758bd5
Create Date: 2023-04-06 12:33:29.565365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "cb2cedf37b19"
down_revision = "c6ff14758bd5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracelog", schema=None) as batch_op:
        batch_op.alter_column(
            "action",
            existing_type=mysql.INTEGER(),
            type_=sa.String(length=25),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "result",
            existing_type=mysql.INTEGER(),
            type_=sa.String(length=25),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracelog", schema=None) as batch_op:
        batch_op.alter_column(
            "result",
            existing_type=sa.String(length=25),
            type_=mysql.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "action",
            existing_type=sa.String(length=25),
            type_=mysql.INTEGER(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
