"""empty message

Revision ID: e149c7279568
Revises: 5987837b4638
Create Date: 2023-04-04 15:19:02.566487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e149c7279568"
down_revision = "5987837b4638"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracelog", schema=None) as batch_op:
        batch_op.alter_column(
            "result",
            existing_type=mysql.VARCHAR(length=512),
            type_=sa.Integer(),
            existing_nullable=True,
        )
        batch_op.create_index(
            batch_op.f("ix_tracelog_result"), ["result"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracelog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracelog_result"))
        batch_op.alter_column(
            "result",
            existing_type=sa.Integer(),
            type_=mysql.VARCHAR(length=512),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
