"""added defacement tracker table

Revision ID: e810af4e6074
Revises: 9e81d084bf65
Create Date: 2024-11-26 10:26:10.524173

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e810af4e6074"
down_revision = "9e81d084bf65"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "defacementtracker",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("hash", sa.String(length=30), nullable=False),
        sa.Column("picture_hash", sa.String(length=30), nullable=False),
        sa.Column("defaced", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("defacementtracker", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_defacementtracker_defaced"), ["defaced"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_defacementtracker_hash"), ["hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_defacementtracker_picture_hash"),
            ["picture_hash"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("defacementtracker", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_defacementtracker_picture_hash"))
        batch_op.drop_index(batch_op.f("ix_defacementtracker_hash"))
        batch_op.drop_index(batch_op.f("ix_defacementtracker_defaced"))

    op.drop_table("defacementtracker")
    # ### end Alembic commands ###
