upstream websocket_nodes {
    ip_hash;

    server flask_ws1:5050;
    server flask_ws2:5050;
    server flask_ws3:5050;
}

upstream webserver_nodes {
    server flask_web1:5050;
    server flask_web2:5050;
}

server {
    listen 80;
    server_name _;

    location / {
        include proxy_params;
        proxy_pass http://webserver_nodes;
    }

    location /static {
        alias /app/static;
        expires 30d;
    }

    location /socket.io {
        include proxy_params;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://websocket_nodes/socket.io;
    }
}
